version: '3'
services:
  wanglab-coder-template:
    build:
      context: .
      dockerfile: Dockerfile.coder
    container_name: wanglab-coder-template
    volumes:
      - .:/config/workspace:rw
    ports:
    - "8443:8443"
    restart: unless-stopped
    networks:
    - default
    - nginx-net
    deploy:
     resources:
       limits:
         memory: 16000M
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
      - PASSWORD=${LOGINPASSWORD:-PASSWORD}
      - VIRTUAL_HOST=codertemplate.wanglab.science
      - VIRTUAL_PORT=8443
      - LETSENCRYPT_HOST=codertemplate.wanglab.science
      - LETSENCRYPT_EMAIL=mwang87@gmail.com


networks:
  nginx-net:
    external:
      name: nginx-net