
version: '3'
services:
  wanglab-jupyter-qiime2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wanglab-jupyter-qiime2
    volumes:
      - .:/home/jovyan:rw
    ports:
    - "9574:9000"
    restart: unless-stopped
    command: /home/jovyan/run_server.sh
    networks:
    - default
    - nginx-net
    deploy:
     resources:
       limits:
         memory: 16000M
    environment:
      VIRTUAL_HOST: qiime2.wanglab.science
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: qiime2.wanglab.science
      LETSENCRYPT_EMAIL: mwang87@gmail.com
      NB_PASSWORD: ${LOGINPASSWORD:-PASSWORD}

networks:
  nginx-net:
    external:
      name: nginx-net